backend:
  name: git-gateway
  branch: main
media_folder: "uploads"
public_folder: "/uploads"
collections:
  - name: "folk"
    label: "Народні пісні"
    folder: "data/folk"
    create: true
    extension: "json"
    format: "json"
    slug: "{{slug}}"
    fields:
      - {label: "Назва", name: "title", widget: "string"}
      - {label: "Опис", name: "description", widget: "text"}
      - {label: "PDF", name: "pdf", widget: "file"}
      - {label: "Обкладинка", name: "image", widget: "image"}
