backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

locale: 'uk'

collections:
  - name: "news"
    label: "Новини"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: "json"
    fields:
      - {label: Заголовок, name: title, widget: string}
      - {label: Дата, name: date, widget: datetime}
      - {label: Локація, name: location, widget: string, required: false}
      - {label: Анонс, name: excerpt, widget: text}
      - {label: Текст, name: body, widget: text}
  - name: "composers"
    label: "Композитори"
    folder: "content/composers"
    create: true
    slug: "{{slug}}"
    format: "json"
    fields:
      - {label: Ім'я, name: name, widget: string}
      - {label: Слаг (латиниця), name: slug, widget: string}
      - {label: Фото, name: photo, widget: image, required: false}
      - {label: Короткий опис, name: summary, widget: text, required: false}
      - {label: Біографія, name: bio, widget: text, required: false}
      - {label: YouTube (embed URL), name: youtube, widget: string, required: false}
      - label: Партитури
        name: scores
        widget: list
        fields:
          - {label: Назва, name: title, widget: string, required: false}
          - {label: Голоси, name: voices, widget: string, required: false}
          - {label: Сторінок, name: pages, widget: number, required: false}
          - label: Стара редакція
            name: old
            widget: object
            required: false
            fields:
              - {label: Прев'ю, name: preview, widget: image, required: false}
              - {label: PDF, name: pdf, widget: file, required: false}
          - label: Нова редакція
            name: new
            widget: object
            required: false
            fields:
              - {label: Прев'ю, name: preview, widget: image, required: false}
              - {label: PDF, name: pdf, widget: file, required: false}
  - name: "scores"
    label: "Партитури (розділи)"
    files:
      - label: "Народні пісні"
        name: "folk"
        file: "content/scores/folk.json"
        format: "json"
        fields:
          - label: Пари творів
            name: pairs
            widget: list
            fields:
              - {label: Назва, name: name, widget: string}
              - label: Стара
                name: old
                widget: object
                fields:
                  - {label: Назва, name: title, widget: string, required: false}
                  - {label: Голоси, name: voices, widget: string, required: false}
                  - {label: Сторінок, name: pages, widget: number, required: false}
                  - {label: Прев'ю, name: preview, widget: image, required: false}
                  - {label: PDF, name: pdf, widget: file, required: false}
              - label: Нова
                name: new
                widget: object
                fields:
                  - {label: Назва, name: title, widget: string, required: false}
                  - {label: Голоси, name: voices, widget: string, required: false}
                  - {label: Сторінок, name: pages, widget: number, required: false}
                  - {label: Прев'ю, name: preview, widget: image, required: false}
                  - {label: PDF, name: pdf, widget: file, required: false}
      - label: "Духовні твори"
        name: "spiritual"
        file: "content/scores/spiritual.json"
        format: "json"
        fields:
          - label: Партитури
            name: scores
            widget: list
            fields:
              - {label: Назва, name: title, widget: string}
              - {label: Голоси, name: voices, widget: string, required: false}
              - {label: Сторінок, name: pages, widget: number, required: false}
              - {label: Прев'ю, name: preview, widget: image, required: false}
              - {label: PDF, name: pdf, widget: file, required: false}
  - name: "shop"
    label: "Крамниця"
    files:
      - label: "Товари"
        name: "products"
        file: "content/shop/products.json"
        format: "json"
        fields:
          - label: Продукти
            name: products
            widget: list
            fields:
              - {label: Назва, name: title, widget: string}
              - {label: Формат, name: format, widget: string, required: false}
              - {label: Ціна (₴), name: price, widget: number, required: false}
              - {label: Зображення, name: image, widget: image, required: false}
              - {label: Файл/посилання, name: file, widget: file, required: false}
